# Credentials Twilio (OBLIGATOIRE pour les SMS)
TWILIO_ACCOUNT_SID=ACabfcb37ffd779fca3dfdb47a028352a7
TWILIO_AUTH_TOKEN=0772f603bc966976e8a64b7234ab510e
TWILIO_PHONE_NUMBER=+17754297649

# Credentials Meta (OBLIGATOIRE pour WhatsApp)
TWILIO_WHATSAPP_TOKEN=0772f603bc966976e8a64b7234ab510e
TWILIO_WHATSAPP_PHONE_NUMBER=+15557888072
TWILIO_WHATSAPP_SID=ACabfcb37ffd779fca3dfdb47a028352a7