name: Run App

on:
  workflow_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script
        run: |
          python app.py
