# fichier .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run my script
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}  # ← Votre secret ici
      run: |
        python my_script.py
